const BOOKS = [
  {
    id: 1,
    title: 'Way of the Kings',
    planet: 'Roshar',
    image: '../../public/cover/wayofthekings.png',
    author: 'Brandon Sanderson',
    totalPages: 1008,
    pagesRead: 1008,
  },
  {
    id: 2,
    title: 'Words of Radiance',
    planet: 'Roshar',
    image: '../../public/cover/wordsofradiance.jpeg',
    author: 'Brandon Sanderson',
    totalPages: 1088,
    pagesRead: 1088,
  },
  {
    id: 3,
    title: 'Edgedancer',
    planet: 'Roshar',
    image: '../../public/cover/edgedancer.jpeg',
    author: 'Brandon Sanderson',
    totalPages: 272,
    pagesRead: 272,
  },
  {
    id: 4,
    title: 'Oathbringer',
    planet: 'Roshar',
    image: '../../public/cover/oathbringer.jpeg',
    author: 'Brandon Sanderson',
    totalPages: 1220,
    pagesRead: 1220,
  },
  {
    id: 5,
    title: 'Dawnshard',
    planet: 'Roshar',
    image: '../../public/cover/dawnshard.jpeg',
    author: 'Brandon Sanderson',
    totalPages: 269,
    pagesRead: 269,
  },

  {
    id: 6,
    title: 'Rythm of War',
    planet: 'Sel',
    image: '../../public/cover/rythmofwar.jpeg ',
    author: 'Brandon Sanderson',
    totalPages: 1232,
    pagesRead: 1232,
  },

  {
    id: 7,
    title: 'Elantris',
    planet: 'Nalthis',
    image: '../../public/cover/elantris.jpeg',
    author: 'Brandon Sanderson',
    totalPages: 592,
    pagesRead: 592,
  },
  {
    id: 8,
    title: 'Warbreaker',
    planet: 'Sel',
    image: '../../public/cover/warbreaker.jpeg',
    author: 'Brandon Sanderson',
    totalPages: 592,
    pagesRead: 592,
  },
  {
    id: 9,
    title: 'The Final Empire',
    planet: 'Scadrial',
    image: '../../public/cover/thefinalempire.jpeg',
    author: 'Brandon Sanderson',
    totalPages: 541,
    pagesRead: 541,
  },
  {
    id: 10,
    title: 'The well of ascension',
    planet: 'Scadrial',
    image: '../../public/cover/thewellofascension.jpeg',
    author: 'Brandon Sanderson',
    totalPages: 590,
    pagesRead: 590,
  },
  {
    id: 11,
    title: 'The Hero of ages',
    planet: 'Scadrial',
    image: '../../public/cover/theheroofages.jpeg',
    author: 'Brandon Sanderson',
    totalPages: 572,
    pagesRead: 572,
  },
  {
    id: 12,
    title: 'Secret History',
    planet: 'Scadrial',
    image: '../../public/cover/secrethistory.jpeg',
    author: 'Brandon Sanderson',
    totalPages: 100,
    pagesRead: 100,
  },
  {
    id: 13,
    title: 'Alloy of law',
    planet: 'Scadrial',
    image: '../../public/cover/thealloyoflaw.jpeg',
    author: 'Brandon Sanderson',
    totalPages: 332,
    pagesRead: 332,
  },
  {
    id: 14,
    title: 'Shadows of self',
    planet: 'Scadrial',
    image: '../../public/cover/shadowsofself.jpeg',
    author: 'Brandon Sanderson',
    totalPages: 383,
    pagesRead: 383,
  },
  {
    id: 15,
    title: 'The bands of mourning',
    planet: 'Scadrial',
    image: '../../public/cover/thebandsofmourning.jpeg',
    author: 'Brandon Sanderson',
    totalPages: 447,
    pagesRead: 447,
  },
  {
    id: 16,
    title: 'The lost Metal',
    planet: 'Scadrial',
    image: 'b../../public/cover/thelostmetal.jpeg',
    author: 'Brandon Sanderson',
    totalPages: 507,
    pagesRead: 507,
  },
  {
    id: 17,
    title: 'Tress of the emerald sea',
    planet: 'Scadrial',
    image: '../../public/cover/treesoftheemeraldsea.jpeg',
    author: 'Brandon Sanderson',
    totalPages: 479,
    pagesRead: 479,
  },
  {
    id: 18,
    title: 'Yumi and the nightmare painter',
    planet: 'Scadrial',
    image: '../../public/cover/yumiandthenightmarepainter.jpeg',
    author: 'Brandon Sanderson',
    totalPages: 479,
    pagesRead: 479,
  },
  {
    id: 19,
    title: 'The sunlit man',
    planet: 'Scadrial',
    image: '../../public/cover/thesunlitman.jpeg',
    author: 'Brandon Sanderson',
    totalPages: 529,
    pagesRead: 335,
  },
  {
    id: 20,
    title: 'White Sand',
    planet: 'Scadrial',
    image: '../../public/cover/whitesand.jpeg',
    author: 'Brandon Sanderson',
    totalPages: 100,
    pagesRead: 0,
  },
  {
    id: 21,
    title: 'Arcanum unbounded',
    planet: 'Scadrial',
    image: '../../public/cover/arcanumunbounded.jpeg',
    author: 'Brandon Sanderson',
    totalPages: 100,
    pagesRead: 100,
  },
];

export default BOOKS;
