const COSMERE = [
  {
    id: 1,
    title: 'Way of the Kings',
    planet: 'Roshar',
    image: 'elcamino.jpg',
    author: 'Brandon Sanderson',
  },
  {
    id: 2,
    title: 'Words of Radiance',
    planet: 'Roshar',
    image: 'words.jpg',
    author: 'Brandon Sanderson',
  },
  {
    id: 3,
    title: 'Edgedancer',
    planet: 'Roshar',
    image: 'Edgedancer.jpg',
    author: 'Brandon Sanderson',
  },
  {
    id: 4,
    title: 'Oathbringer',
    planet: 'Roshar',
    image: 'Oathbringer.jpg',
    author: 'Brandon Sanderson',
  },
  {
    id: 5,
    title: 'Dawnshard',
    planet: 'Roshar',
    image: 'Dawnshard.jpg',
    author: 'Brandon Sanderson',
  },

  {
    id: 6,
    title: 'Rythm of War',
    planet: 'Sel',
    image: 'warbreaker.jpg',
    author: 'Brandon Sanderson',
  },

  {
    id: 7,
    title: 'Elantris',
    planet: 'Nalthis',
    image: 'elantris.jpg',
    author: 'Brandon Sanderson',
  },
  {
    id: 8,
    title: 'Warbreaker',
    planet: 'Sel',
    image: 'warbreaker.jpg',
    author: 'Brandon Sanderson',
  },
  {
    id: 9,
    title: 'Mistborn',
    planet: 'Scadrial',
    image: 'mistborn.jpg',
    author: 'Brandon Sanderson',
  },
  {
    id: 10,
    title: 'The well of ascension',
    planet: 'Scadrial',
    image: 'well.jpg',
    author: 'Brandon Sanderson',
  },
  {
    id: 11,
    title: 'Hero of ages',
    planet: 'Scadrial',
    image: 'hero.jpg',
    author: 'Brandon Sanderson',
  },
  {
    id: 12,
    title: 'Secret Historu',
    planet: 'Scadrial',
    image: 'secret.jpg',
    author: 'Brandon Sanderson',
  },
  {
    id: 13,
    title: 'Allow of law',
    planet: 'Scadrial',
    image: 'allow.jpg',
    author: 'Brandon Sanderson',
  },
  {
    id: 14,
    title: 'Shadows of self',
    planet: 'Scadrial',
    image: 'shadows.jpg',
    author: 'Brandon Sanderson',
  },
  {
    id: 15,
    title: 'The bands of mourning',
    planet: 'Scadrial',
    image: 'bands.jpg',
    author: 'Brandon Sanderson',
  },
  {
    id: 16,
    title: 'The lost Metal',
    planet: 'Scadrial',
    image: 'bands.jpg',
    author: 'Brandon Sanderson',
  },
  {
    id: 17,
    title: 'Tress of the emerald sea',
    planet: 'Scadrial',
    image: 'trees.jpg',
    author: 'Brandon Sanderson',
  },
  {
    id: 18,
    title: 'Yumi and the nightmare painter',
    planet: 'Scadrial',
    image: 'yumi.jpg',
    author: 'Brandon Sanderson',
  },
  {
    id: 19,
    title: 'The sunlit man',
    planet: 'Scadrial',
    image: 'sunlit.jpg',
    author: 'Brandon Sanderson',
  },
  {
    id: 20,
    title: 'White Sand',
    planet: 'Scadrial',
    image: 'Sand.jpg',
    author: 'Brandon Sanderson',
  },
  {
    id: 21,
    title: 'Arcanum unbounded',
    planet: 'Scadrial',
    image:
      'https://coppermind.net/w/images/thumb/Arcanum_Unbounded.jpg/300px-Arcanum_Unbounded.jpg',
    author: 'Brandon Sanderson',
  },
];

export default COSMERE;
